<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controls\D2DControl\**" />
    <Compile Remove="Models\DrawingObjects\**" />
    <Compile Remove="Resources\Shaders\**" />
    <EmbeddedResource Remove="Controls\D2DControl\**" />
    <EmbeddedResource Remove="Models\DrawingObjects\**" />
    <EmbeddedResource Remove="Resources\Shaders\**" />
    <None Remove="Controls\D2DControl\**" />
    <None Remove="Models\DrawingObjects\**" />
    <None Remove="Resources\Shaders\**" />
    <Page Remove="Controls\D2DControl\**" />
    <Page Remove="Models\DrawingObjects\**" />
    <Page Remove="Resources\Shaders\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controls\D3DControl\D3D11ImageSource.cs" />
    <Compile Remove="Controls\D3DControl\D3dControl.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoGlyphBatcher.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoPointLabelLayout.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoPointTextAssembler.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\TextLayoutCache.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\TextMeshBuilder.cs" />
    <Compile Remove="Controls\Direct2DDxfControl.cs" />
    <Compile Remove="Converters\CogoPointColorConverter.cs" />
    <Compile Remove="Converters\CogoPointScaleConverter.cs" />
    <Compile Remove="Converters\CogoPointToggleButtonConverter.cs" />
    <Compile Remove="Converters\ColorToBrushConverter.cs" />
    <Compile Remove="Converters\KeyValueToValueConverter.cs" />
    <Compile Remove="Converters\Matrix3x2ToScaleConverter .cs" />
    <Compile Remove="Converters\Matrix3x2ToWindowsMatrixConverter.cs" />
    <Compile Remove="Converters\PointCenteringConverter.cs" />
    <Compile Remove="Converters\PointTransformer.cs" />
    <Compile Remove="Converters\SelectionModeEnumConverter.cs" />
    <Compile Remove="Converters\SelectionModeEnumToBooleanConverter.cs" />
    <Compile Remove="Helpers\ChainPointSettingHelper.cs" />
    <Compile Remove="Helpers\DxfHelper.cs" />
    <Compile Remove="Helpers\Vector2EqualityComparer.cs" />
    <Compile Remove="Helpers\VectorEqualityComparer.cs" />
    <Compile Remove="Models\CadManager.cs" />
    <Compile Remove="Models\Enums.cs" />
    <Compile Remove="Models\OffscreenBitmap.cs" />
    <Compile Remove="Models\OffscreenBitmapManager.cs" />
    <Compile Remove="Models\PointRendering\CogoPointTextVerticesDict.cs" />
    <Compile Remove="Services\DxfService.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controls\D3DControl\Shaders\PointTextShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\TestShader.hlsl" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Styles\BorderWidgetsRadioButton.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
    <PackageReference Include="FreeTypeSharp" Version="3.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="9.0.4" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="netDxf" Version="2023.11.10" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Testing\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ColorPicker">
      <HintPath>..\..\ColorPicker\src\ColorPicker\obj\Debug\net8.0-windows\ColorPicker.dll</HintPath>
    </Reference>
    <Reference Include="ColorPicker.Models">
      <HintPath>..\..\ColorPicker\src\ColorPicker.Models\bin\Debug\net8.0\ColorPicker.Models.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Styles\BorderWidgetsButton.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Styles\ValidationTextBox.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
