<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controls\D2DControl\**" />
    <Compile Remove="Lib\**" />
    <Compile Remove="Resources\Shaders\**" />
    <EmbeddedResource Remove="Controls\D2DControl\**" />
    <EmbeddedResource Remove="Lib\**" />
    <EmbeddedResource Remove="Resources\Shaders\**" />
    <None Remove="Controls\D2DControl\**" />
    <None Remove="Lib\**" />
    <None Remove="Resources\Shaders\**" />
    <Page Remove="Controls\D2DControl\**" />
    <Page Remove="Lib\**" />
    <Page Remove="Resources\Shaders\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controls\D3DControl\D3D11ImageSource.cs" />
    <Compile Remove="Controls\D3DControl\D3dControl.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoGlyphBatcher.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoPointLabelLayout.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoPointTextAssembler.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\FontBoxMetrics.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\IRenderStateUpdater.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\TextLayoutCache.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\TextMeshBuilder.cs" />
    <Compile Remove="Controls\Direct2DDxfControl.cs" />
    <Compile Remove="Converters\CenterTranslationConverter.cs" />
    <Compile Remove="Converters\CogoPointColorConverter.cs" />
    <Compile Remove="Converters\CogoPointScaleConverter.cs" />
    <Compile Remove="Converters\CogoPointToggleButtonConverter.cs" />
    <Compile Remove="Converters\KeyValueToValueConverter.cs" />
    <Compile Remove="Converters\Matrix3x2ToScaleConverter .cs" />
    <Compile Remove="Converters\Matrix3x2ToWindowsMatrixConverter.cs" />
    <Compile Remove="Converters\PointCenteringConverter.cs" />
    <Compile Remove="Converters\PointMatrixTransformationConverter.cs" />
    <Compile Remove="Converters\PointTransformer.cs" />
    <Compile Remove="Converters\SelectionModeEnumConverter.cs" />
    <Compile Remove="Converters\SelectionModeEnumToBooleanConverter.cs" />
    <Compile Remove="Helpers\ChainPointSettingHelper.cs" />
    <Compile Remove="Helpers\DxfHelper.cs" />
    <Compile Remove="Helpers\Vector2EqualityComparer.cs" />
    <Compile Remove="Helpers\VectorEqualityComparer.cs" />
    <Compile Remove="Models\CogoPointRepository.cs" />
    <Compile Remove="Models\Enums.cs" />
    <Compile Remove="Models\LffFontRendering\FontManager.cs" />
    <Compile Remove="Models\LffFontRendering\TextRenderStyleResolver.cs" />
    <Compile Remove="Models\OffscreenBitmap.cs" />
    <Compile Remove="Models\OffscreenBitmapManager.cs" />
    <Compile Remove="Models\PointRendering\CogoPointTextVerticesDict.cs" />
    <Compile Remove="Models\Printing\PageSize.cs" />
    <Compile Remove="Services\D3dDxfRenderHost.cs" />
    <Compile Remove="Services\DxfService.cs" />
    <Compile Remove="Services\Exporting\ILayoutRenderHost.cs" />
    <Compile Remove="Services\Exporting\LayoutPdfExporter.cs" />
    <Compile Remove="Views\Assorted\InlineEditingHelper.cs" />
    <Compile Remove="Views\UserControls\LayoutControl.xaml.cs" />
    <Compile Remove="Views\UserControls\LayoutPreviewControl.xaml.cs" />
    <Compile Remove="Views\UserControls\LayoutsListViewControl.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Bold.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-BoldItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Italic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Noto\NotoSans-Regular.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Black.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BlackItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Bold.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-BoldItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Italic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Light.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-LightItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Medium.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-MediumItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Regular.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-Thin.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\Roboto-ThinItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Bold.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-BoldItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Italic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Light.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-LightItalic.ttf" />
    <Content Remove="C:\Users\fcraw\.nuget\packages\materialdesignthemes\5.3.0\contentFiles\any\net8.0-windows7.0\Resources\Roboto\RobotoCondensed-Regular.ttf" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controls\D3DControl\Shaders\CircleGlowShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\PointTextShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\SigPointShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\TestShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\TextGlowShader.hlsl" />
    <None Remove="Resources\Fonts\amiri-regular.lff" />
    <None Remove="Resources\Fonts\azomix.lff" />
    <None Remove="Resources\Fonts\azomix_i.lff" />
    <None Remove="Resources\Fonts\cursive.lff" />
    <None Remove="Resources\Fonts\cyrillic_ii.lff" />
    <None Remove="Resources\Fonts\gothgbt.lff" />
    <None Remove="Resources\Fonts\gothgrt.lff" />
    <None Remove="Resources\Fonts\gothitt.lff" />
    <None Remove="Resources\Fonts\greekc.lff" />
    <None Remove="Resources\Fonts\greekcs.lff" />
    <None Remove="Resources\Fonts\greekp.lff" />
    <None Remove="Resources\Fonts\greeks.lff" />
    <None Remove="Resources\Fonts\greek_ol.lff" />
    <None Remove="Resources\Fonts\hershey.readme" />
    <None Remove="Resources\Fonts\iso.lff" />
    <None Remove="Resources\Fonts\iso3098.lff" />
    <None Remove="Resources\Fonts\iso3098_i.lff" />
    <None Remove="Resources\Fonts\italicc.lff" />
    <None Remove="Resources\Fonts\italiccs.lff" />
    <None Remove="Resources\Fonts\italict.lff" />
    <None Remove="Resources\Fonts\kochigothic.lff" />
    <None Remove="Resources\Fonts\kochimincho.lff" />
    <None Remove="Resources\Fonts\kst32b.lff" />
    <None Remove="Resources\Fonts\lc_opengost-ar.lff" />
    <None Remove="Resources\Fonts\lc_opengost-br.lff" />
    <None Remove="Resources\Fonts\opengosttypea-regular.lff" />
    <None Remove="Resources\Fonts\opengosttypeb-regular.lff" />
    <None Remove="Resources\Fonts\romanc.lff" />
    <None Remove="Resources\Fonts\romancs.lff" />
    <None Remove="Resources\Fonts\romand.lff" />
    <None Remove="Resources\Fonts\romanp.lff" />
    <None Remove="Resources\Fonts\romans.lff" />
    <None Remove="Resources\Fonts\romansi.lff" />
    <None Remove="Resources\Fonts\romant.lff" />
    <None Remove="Resources\Fonts\scriptc.lff" />
    <None Remove="Resources\Fonts\scripts.lff" />
    <None Remove="Resources\Fonts\simplex.lff" />
    <None Remove="Resources\Fonts\standard.lff" />
    <None Remove="Resources\Fonts\syastro.lff" />
    <None Remove="Resources\Fonts\symap.lff" />
    <None Remove="Resources\Fonts\symath.lff" />
    <None Remove="Resources\Fonts\symbol.lff" />
    <None Remove="Resources\Fonts\symbol_misc1.lff" />
    <None Remove="Resources\Fonts\symbol_misc2.lff" />
    <None Remove="Resources\Fonts\symeteo.lff" />
    <None Remove="Resources\Fonts\symusic.lff" />
    <None Remove="Resources\Fonts\unicode.lff" />
    <None Remove="Resources\Images\IQ Contracting - Logo %28Square%29.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Styles\BorderWidgetsRadioButton.xaml" />
    <Page Remove="Styles\ListViewStyle.xaml" />
    <Page Remove="Styles\ValidationTemplate.xaml" />
    <Page Remove="Views\UserControls\LayoutControl.xaml" />
    <Page Remove="Views\UserControls\LayoutPreviewControl.xaml" />
    <Page Remove="Views\UserControls\LayoutsListViewControl.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\Fonts\amiri-regular.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\azomix.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\azomix_i.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\cursive.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\cyrillic_ii.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\gothgbt.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\gothgrt.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\gothitt.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\greekc.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\greekcs.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\greekp.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\greeks.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\greek_ol.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\hershey.readme">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\iso.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\iso3098.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\iso3098_i.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\italicc.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\italiccs.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\italict.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\kochigothic.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\kochimincho.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\kst32b.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\lc_opengost-ar.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\lc_opengost-br.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\opengosttypea-regular.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\opengosttypeb-regular.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\romanc.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\romancs.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\romand.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\romanp.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\romans.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\romansi.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\romant.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\scriptc.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\scripts.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\simplex.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\standard.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\syastro.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\symap.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\symath.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\symbol.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\symbol_misc1.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\symbol_misc2.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\symeteo.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\symusic.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\Fonts\unicode.lff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
    <PackageReference Include="FreeTypeSharp" Version="3.0.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="9.0.4" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="netDxf" Version="2023.11.10" />
    <PackageReference Include="PdfiumViewer" Version="2.13.0" />
    <PackageReference Include="PdfiumViewer.Native.x86_64.v8-xfa" Version="2018.4.8.256" />
    <PackageReference Include="PdfSharpCore" Version="1.3.67" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Testing\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ColorPicker\src\ColorPicker\ColorPicker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\IQ Contracting - Logo (Square).jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Styles\BorderWidgetsButton.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
