<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <LangVersion>preview</LangVersion>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controls\D2DControl\**" />
    <Compile Remove="Lib\**" />
    <Compile Remove="Resources\Shaders\**" />
    <EmbeddedResource Remove="Controls\D2DControl\**" />
    <EmbeddedResource Remove="Lib\**" />
    <EmbeddedResource Remove="Resources\Shaders\**" />
    <None Remove="Controls\D2DControl\**" />
    <None Remove="Lib\**" />
    <None Remove="Resources\Shaders\**" />
    <Page Remove="Controls\D2DControl\**" />
    <Page Remove="Lib\**" />
    <Page Remove="Resources\Shaders\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Controls\D3DControl\D3D11ImageSource.cs" />
    <Compile Remove="Controls\D3DControl\D3dControl.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoGlyphBatcher.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoPointLabelLayout.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\CogoPointTextAssembler.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\FontBoxMetrics.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\IRenderStateUpdater.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\TextLayoutCache.cs" />
    <Compile Remove="Controls\D3DControl\Rendering\Text\TextMeshBuilder.cs" />
    <Compile Remove="Controls\Direct2DDxfControl.cs" />
    <Compile Remove="Converters\CenterTranslationConverter.cs" />
    <Compile Remove="Converters\CogoPointColorConverter.cs" />
    <Compile Remove="Converters\CogoPointScaleConverter.cs" />
    <Compile Remove="Converters\CogoPointToggleButtonConverter.cs" />
    <Compile Remove="Converters\KeyValueToValueConverter.cs" />
    <Compile Remove="Converters\Matrix3x2ToScaleConverter .cs" />
    <Compile Remove="Converters\Matrix3x2ToWindowsMatrixConverter.cs" />
    <Compile Remove="Converters\PointCenteringConverter.cs" />
    <Compile Remove="Converters\PointMatrixTransformationConverter.cs" />
    <Compile Remove="Converters\PointTransformer.cs" />
    <Compile Remove="Converters\SelectionModeEnumConverter.cs" />
    <Compile Remove="Converters\SelectionModeEnumToBooleanConverter.cs" />
    <Compile Remove="Helpers\ChainPointSettingHelper.cs" />
    <Compile Remove="Helpers\DxfHelper.cs" />
    <Compile Remove="Helpers\Vector2EqualityComparer.cs" />
    <Compile Remove="Helpers\VectorEqualityComparer.cs" />
    <Compile Remove="Models\Enums.cs" />
    <Compile Remove="Models\OffscreenBitmap.cs" />
    <Compile Remove="Models\OffscreenBitmapManager.cs" />
    <Compile Remove="Models\PointRendering\CogoPointTextVerticesDict.cs" />
    <Compile Remove="Models\Printing\PageSize.cs" />
    <Compile Remove="Services\D3dDxfRenderHost.cs" />
    <Compile Remove="Services\DxfService.cs" />
    <Compile Remove="Services\LayoutExporting\ILayoutRenderHost.cs" />
    <Compile Remove="Services\LayoutExporting\LayoutPdfExporter.cs" />
    <Compile Remove="Views\Assorted\InlineEditingHelper.cs" />
    <Compile Remove="Views\UserControls\LayoutControl.xaml.cs" />
    <Compile Remove="Views\UserControls\LayoutsListViewControl.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controls\D3DControl\Shaders\CircleGlowShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\PointTextShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\SigPointShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\TestShader.hlsl" />
    <None Remove="Controls\D3DControl\Shaders\TextGlowShader.hlsl" />
    <None Remove="Resources\Images\IQ Contracting - Logo %28Square%29.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Styles\BorderWidgetsRadioButton.xaml" />
    <Page Remove="Styles\ListViewStyle.xaml" />
    <Page Remove="Styles\ValidationTemplate.xaml" />
    <Page Remove="Views\UserControls\LayoutControl.xaml" />
    <Page Remove="Views\UserControls\LayoutsListViewControl.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
    <PackageReference Include="FreeTypeSharp" Version="3.0.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="9.0.4" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="netDxf" Version="2023.11.10" />
    <PackageReference Include="PdfSharpCore" Version="1.3.67" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Testing\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\ColorPicker\src\ColorPicker\ColorPicker.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Images\IQ Contracting - Logo (Square).jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Styles\BorderWidgetsButton.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
